name: "beamform_cc_gpu"
backend: "onnxruntime"
max_batch_size: 4096
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 1000, 8 ]
  },
  {
    name: "input__1"
    data_type: TYPE_FP32
    dims: [ 8, 1 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1000, 2 ]
  }
]


dynamic_batching {}

instance_group [
	{
		count: 1
		kind: KIND_GPU
	}
]


