/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(863aefe19e2ad286357f202581479ce4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/add_cc.h>
// pydoc.h is automatically generated in the build directory
#include <add_cc_pydoc.h>

void bind_add_cc(py::module& m)
{

    using add_cc = gr::torchdsp::add_cc;


    py::class_<add_cc, gr::block, gr::basic_block, std::shared_ptr<add_cc>>(m, "add_cc", D(add_cc))

        .def(py::init(&add_cc::make), py::arg("num_inputs"), py::arg("device_num"), D(add_cc, make))


        ;
}
