/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fft_vcc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9d6edd2db42a5939248dc6dbf2964882)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/fft_vcc.h>
// pydoc.h is automatically generated in the build directory
#include <fft_vcc_pydoc.h>

void bind_fft_vcc(py::module& m)
{

    using fft_vcc = gr::torchdsp::fft_vcc;


    py::class_<fft_vcc, gr::sync_block, gr::block, gr::basic_block, std::shared_ptr<fft_vcc>>(m, "fft_vcc", D(fft_vcc))

        .def(py::init(&fft_vcc::make), py::arg("fft_len"), py::arg("device_num"), D(fft_vcc, make))


        ;
}
