/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multiply_const_vcvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1a8f18920a34ee811b01835178377fe6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/multiply_const_vcvc.h>
// pydoc.h is automatically generated in the build directory
#include <multiply_const_vcvc_pydoc.h>

void bind_multiply_const_vcvc(py::module& m)
{

    using multiply_const_vcvc = gr::torchdsp::multiply_const_vcvc;


    py::class_<multiply_const_vcvc, gr::sync_block, gr::block, gr::basic_block, std::shared_ptr<multiply_const_vcvc>>(
        m, "multiply_const_vcvc", D(multiply_const_vcvc))

        .def(py::init(&multiply_const_vcvc::make),
             py::arg("constant"),
             py::arg("device_num"),
             D(multiply_const_vcvc, make))


        ;
}
