/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(torch_fir_filter_ccc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(40017ec2b43b39dd642cc6fadfc3225a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/torch_fir_filter_ccc.h>
// pydoc.h is automatically generated in the build directory
#include <torch_fir_filter_ccc_pydoc.h>

void bind_torch_fir_filter_ccc(py::module& m)
{

    using torch_fir_filter_ccc    = ::gr::torchdsp::torch_fir_filter_ccc;


    py::class_<torch_fir_filter_ccc, gr::sync_decimator,
        std::shared_ptr<torch_fir_filter_ccc>>(m, "torch_fir_filter_ccc", D(torch_fir_filter_ccc))

        .def(py::init(&torch_fir_filter_ccc::make),
           py::arg("taps"),
           py::arg("downsample_rate"),
           py::arg("device_num"),
           D(torch_fir_filter_ccc,make)
        )
        



        ;




}








