/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(torch_fft_vcc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fde5818d35f4172a3e346f4a728c9128)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/torch_fft_vcc.h>
// pydoc.h is automatically generated in the build directory
#include <torch_fft_vcc_pydoc.h>

void bind_torch_fft_vcc(py::module& m)
{

    using torch_fft_vcc    = ::gr::torchdsp::torch_fft_vcc;


    py::class_<torch_fft_vcc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<torch_fft_vcc>>(m, "torch_fft_vcc", D(torch_fft_vcc))

        .def(py::init(&torch_fft_vcc::make),
           py::arg("fft_len"),
           py::arg("device_num"),
           D(torch_fft_vcc,make)
        )
        



        ;




}








