/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(triton_inference.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bb13e82adbad95e8f671736c94571c8d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/triton_inference.h>
// pydoc.h is automatically generated in the build directory
#include <triton_inference_pydoc.h>

void bind_triton_inference(py::module& m)
{

    using triton_inference    = ::gr::torchdsp::triton_inference;


    py::class_<triton_inference, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<triton_inference>>(m, "triton_inference", D(triton_inference))

        .def(py::init(&triton_inference::make),
           py::arg("model_name"),
           py::arg("triton_url") = "localhost:8000",
           D(triton_inference,make)
        )
        



        ;




}








