/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zcu216_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8cc4701efc5d7248a1cd59d61b8bbf1d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/zcu216_source.h>
// pydoc.h is automatically generated in the build directory
#include <zcu216_source_pydoc.h>

void bind_zcu216_source(py::module& m)
{

    using zcu216_source    = ::gr::torchdsp::zcu216_source;


    py::class_<zcu216_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<zcu216_source>>(m, "zcu216_source", D(zcu216_source))

        .def(py::init(&zcu216_source::make),
           D(zcu216_source,make)
        )
        



        ;




}








