name: "add_gpu"
backend: "pytorch"
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 1, 16 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1, 16 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
