name: "add_gpu"
backend: "pytorch"
max_batch_size: 256
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  },
  {
    name: "input__1"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]
dynamic_batching {}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
